name: Release

on:
  push:
    branches:
      - main
#    paths:
#      - "*.py"
      

permissions: read-all

jobs:
  release:
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    uses: ./.github/workflows/release-reusable.yaml
    with:
      config-name:  workflows/config/rd-config.yaml
      oidc_role: arn:aws:iam::901512569142:role/c201-github-oidc-role
      region: eu-west-1
      terraform_dir: "${GITHUB_WORKSPACE}/terraform/app/eu-west-1/test-api/"
      ecr_repo_name: test-repo
    secrets: inherit