name: build-push-deploy-dev

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+rc[0-9]+'

permissions: read-all

jobs:
  build-push:
    permissions: 
      id-token: write
      contents: write
    uses: boldlink/workflows-and-pipelines/.github/workflows/gh001-build-push.yaml@main
    with:
      region: <ecr-repository-region> # e.g eu-west-1
      ecr_repo_name: <ecr-repository-name>
    #secrets: inherit

  deploy-dev:
    needs: build-push
    permissions: 
      id-token: write
      contents: write
    uses: boldlink/workflows-and-pipelines/.github/workflows/gh001-deploy.yaml@main
    with:
      oidc_role: <github-oidc-role-arn> # e.g arn:aws:iam::11111222223:role/github-oidc-role
      region: <region-to deploy-to> # e.g eu-west-1
      terraform_dir: <directory-containing-terraform-files> #e.g "${GITHUB_WORKSPACE}/terraform/app/eu-west-1/python-api/"
      environment: <environment> #e.g dev
    secrets: inherit
