name: Release

on:
  push:
    branches:
      - main
#    paths:
#      - "*.py"
      
permissions: read-all

jobs:
  release:
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    uses: boldlink/workflows-and-pipelines/.github/workflows/gh001-release.yaml@main
    with:
      config-name:  workflows/config/rd-config.yaml
      oidc_role: <github-oidc-role-arn> # e.g arn:aws:iam::11111222223:role/github-oidc-role
      region: <region-to deploy-to> # e.g eu-west-1
      terraform_dir: <directory-containing-terraform-files> #e.g "${GITHUB_WORKSPACE}/terraform/app/eu-west-1/python-api/"
      ecr_repo_name: <ecr-repository-name>
    secrets: inherit
