name: PR Labeler

on:
  workflow_call:
    inputs:
      configuration-path:
        required: true
        type: string
    secrets:
      SLACK_WEBHOOK:
        required: true
jobs:
  pr-labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Current Year
        id: year
        run: echo "year=$(date +'%Y')" >> $GITHUB_OUTPUT

      - uses: TimonVS/pr-labeler-action@v3
        with:
          configuration-path: ${{inputs.configuration-path}}            
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Slack Notification failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_USERNAME: Boldlinksig
          SLACK_MESSAGE: ":bell: Job failed in ${{ github.event.repository.name }} repository."
          SLACK_FOOTER: "Boldlink-SIG ${{ steps.year.outputs.year }}"
          SLACK_COLOR: ${{ job.status }} 
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}