name: build-push

on:
  workflow_call:
    inputs:
      region:
        required: true
        type: string
      ecr_repo_name:
        type: string
        required: true

env:
  TF_VER: '0.14.11'

jobs:
  build_push:
    runs-on: self-hosted
    permissions: 
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v3
        name: checkout repo code 
        with:
          ref: ${{ github.event.base_ref }} 
   
      - name: Query account ID
        id: query-account
        run: |
          echo "account=$(aws sts get-caller-identity --query "Account" --output text)" >> $GITHUB_OUTPUT

      - name: Docker build
        id: tag-image
        run: |
          aws ecr get-login-password --region ${{ inputs.region }} | docker login --username AWS --password-stdin ${{ steps.query-account.outputs.account }}.dkr.ecr.${{ inputs.region }}.amazonaws.com
          docker build -t ${{ steps.query-account.outputs.account }}.dkr.ecr.${{ inputs.region }}.amazonaws.com/${{ inputs.ecr_repo_name }}:${{ github.ref_name }} .
          echo "image=${{ steps.query-account.outputs.account }}.dkr.ecr.${{ inputs.region }}.amazonaws.com/${{ inputs.ecr_repo_name }}:${{ github.ref_name }}" >> $GITHUB_OUTPUT

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.tag-image.outputs.image }}
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"

      - name: Docker push
        id: push-image
        run: |
          docker push ${{ steps.tag-image.outputs.image }}
